services:
  - type: web
    name: groqverse
    env: python
    plan: free
    buildCommand: |
      curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
      tar -xf ffmpeg.tar.xz
      cp ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
      pip install -r requirements.txt
    startCommand: "python backend/app.py"
    envVars:
      - key: GROQ_API_KEY
        value: your_real_key_here
